### ISSUE TITLE
Support nesting.

### ISSUE THREAD

**Issue by jamen** [pixiejs/pixie#4]
Supporting nested tags:

```
Hello {{foo {{bar}} baz}}.
```

Right now, the expression would be considered:

```
foo {{bar
```

I would like it to be:

```
foo {{bar}} baz
```

**Comment by seanc** [comment]
Perhaps you could add a delimiter like jade's `#`, i.e. `p #[a(href="http://github.com") github]`

**Comment by jamen** [comment]
I'm considering using `balanced-match` to do it for me.  Although, I have been waiting for https://github.com/juliangruber/balanced-match/issues/12, perhaps it doesn't matter _too_ much for now...  Since Pixie is still pretty early.

**Comment by jamen** [comment]
I appears balanced match has a `.range` function, which is exactly what i need pretty sure.

**Comment by jamen** [comment]
I decided I wont support nesting.
